spring.jpa:
  database: POSTGRESQL
  hibernate.ddl-auto: none
  show-sql: true

spring.datasource:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/GestioneCondominio
  username: postgres
  password: 5585
  
spring.sql.init:
      platform: postgres
